// Generated by scripts/benchmarks/generate-climate-palette-header.py; do not hand edit.
#pragma once
#include <algorithm>
#include <array>
#include <cmath>
namespace climatepalette {
struct Stop { double position; std::array<unsigned char, 3> rgb; };
inline constexpr std::array<Stop, 8> positiveStops = {{
    Stop{0, {40, 71, 199}},
    Stop{0.15, {32, 157, 237}},
    Stop{0.3, {28, 215, 196}},
    Stop{0.45, {102, 223, 95}},
    Stop{0.6, {203, 235, 52}},
    Stop{0.75, {248, 201, 50}},
    Stop{0.9, {244, 119, 30}},
    Stop{1, {207, 41, 41}}
}};
inline constexpr std::array<Stop, 8> signedStops = {{
    Stop{0, {225, 225, 225}},
    Stop{0.13, {185, 0, 255}},
    Stop{0.27, {45, 0, 255}},
    Stop{0.4, {0, 105, 255}},
    Stop{0.5, {0, 220, 230}},
    Stop{0.67, {0, 205, 70}},
    Stop{0.83, {255, 230, 0}},
    Stop{1, {220, 45, 0}}
}};
inline constexpr double field_surface_wind_low = 0.0;
inline constexpr double field_surface_wind_high = 25.0;
inline constexpr double field_850_wind_low = 0.0;
inline constexpr double field_850_wind_high = 30.0;
inline constexpr double field_500_wind_low = 0.0;
inline constexpr double field_500_wind_high = 40.0;
inline constexpr double field_pressure_low = -30.0;
inline constexpr double field_pressure_high = 30.0;
inline constexpr double field_rain_low = 0.0;
inline constexpr double field_rain_high = 20.0;
inline constexpr double field_annual_rain_low = 0.0;
inline constexpr double field_annual_rain_high = 6000.0;
inline constexpr double field_water_low = 0.0;
inline constexpr double field_water_high = 65.0;
inline constexpr double field_moisture_flux_low = 0.0;
inline constexpr double field_moisture_flux_high = 800.0;
inline constexpr double field_convergence_low = -20.0;
inline constexpr double field_convergence_high = 20.0;
inline constexpr double field_sst_low = -35.0;
inline constexpr double field_sst_high = 35.0;
inline constexpr double field_skin_sst_low = -35.0;
inline constexpr double field_skin_sst_high = 35.0;
inline constexpr double field_sst_oisst_low = -35.0;
inline constexpr double field_sst_oisst_high = 35.0;
inline constexpr double field_air_temperature_low = -54.0;
inline constexpr double field_air_temperature_high = 40.0;
inline constexpr double field_current_low = 0.0;
inline constexpr double field_current_high = 1.0;
inline constexpr double field_storage_depth_low = 0.0;
inline constexpr double field_storage_depth_high = 200.0;
inline constexpr double field_evaporation_low = 0.0;
inline constexpr double field_evaporation_high = 250.0;
inline constexpr double field_surface_radiation_low = -250.0;
inline constexpr double field_surface_radiation_high = 250.0;
inline std::array<unsigned char, 3> colour(double value, double low, double high, bool isSigned) {
    if (!std::isfinite(value) || !(high > low)) return {0, 0, 0};
    double t = isSigned && low < 0 && high > 0 ? (value <= 0 ? .5*(value-low)/(-low) : .5+.5*value/high) : (value-low)/(high-low);
    t = std::clamp(t, 0.0, 1.0);
    const auto& stops = isSigned ? signedStops : positiveStops;
    for (std::size_t i=1; i<stops.size(); ++i) if (t <= stops[i].position) {
        const double f=(t-stops[i-1].position)/(stops[i].position-stops[i-1].position);
        std::array<unsigned char, 3> result{};
        for (int c=0; c<3; ++c) result[c]=static_cast<unsigned char>(std::floor(stops[i-1].rgb[c]+f*(int(stops[i].rgb[c])-int(stops[i-1].rgb[c]))+.5));
        return result;
    }
    return stops.back().rgb;
}
}
